FROM ruby:3.2.11

WORKDIR /rails

# Install development dependencies including build tools
RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      curl \
      git \
      libpq-dev \
      libvips \
      libyaml-dev \
      nodejs \
      npm \
      pkg-config \
      postgresql-client \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

EXPOSE 3000
